name: Update README on Main Branch

on:
  push:
    branches:
      - development

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge to Main
        if: github.ref == 'refs/heads/dev'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin main
          git checkout main
          git merge dev --allow-unrelated-histories
          git push origin main

  generate-readme:
    runs-on: ubuntu-latest
    needs: merge-to-main
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate README
        run: |
          python -m pip install pyyaml
          python -m pip install jinja2
          python readme_generator/update_readme.py
      
      - name: Resolve merge conflicts
        run: |
          git add .
          git commit -m "Merge conflict resolution"
      
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
