name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          sudo su
          apt-get update && apt-get install -y xvfb libfontconfig wkhtmltopdf

      - name: Install requirements.txt
        run: |
          sudo su
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          python3 utils/__init__.py
        working-directory: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
