name: Merge Code to Main Branch from development

on:
  push:
    branches:
      - development

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge to Main
        if: github.ref == 'refs/heads/development'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin main
          git checkout main
          git checkout development
          git rebase --strategy recursive --strategy-option theirs main
          git checkout main
          git merge development --allow-unrelated-histories
          git push origin main

